version: '3.8'

services:
   db:
     image: mysql:5.7.12
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${MYSQL_WORDPRESS_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:5.6.0-php7.4-apache
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: ${MYSQL_WORDPRESS_PASSWORD}
volumes:
    db_data:
